// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresql

import (
	"database/sql"
)

type MarketplaceOrder struct {
	OrderHash   string
	Offerer     string
	IsCancelled bool
	IsValidated bool
	IsFulfilled bool
	Signature   string
	OrderType   string
	StartTime   string
	EndTime     string
	Counter     string
	Salt        string
	Zone        sql.NullString
	ZoneHash    sql.NullString
	CreatedAt   sql.NullTime
	ModifiedAt  sql.NullTime
}

type MarketplaceOrderConsideration struct {
	ID           int32
	OrderHash    string
	TypeNumber   string
	TokenID      string
	TokenAddress string
	StartAmount  string
	EndAmount    string
	Recipient    string
}

type MarketplaceOrderOffer struct {
	ID           int32
	OrderHash    string
	TypeNumber   string
	TokenID      string
	TokenAddress string
	StartAmount  string
	EndAmount    string
}
