// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresql

import (
	"context"
)

type Querier interface {
	DestroyOrders(ctx context.Context, arg DestroyOrdersParams) error
	GetOrder(ctx context.Context, orderHash string) (GetOrderRow, error)
	GetOrderConsideration(ctx context.Context, orderHash string) ([]GetOrderConsiderationRow, error)
	GetOrderHashByConsiderationItem(ctx context.Context, arg GetOrderHashByConsiderationItemParams) ([]GetOrderHashByConsiderationItemRow, error)
	GetOrderHashByOfferItem(ctx context.Context, arg GetOrderHashByOfferItemParams) ([]GetOrderHashByOfferItemRow, error)
	GetOrderOffer(ctx context.Context, orderHash string) ([]GetOrderOfferRow, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	InsertOrderConsideration(ctx context.Context, arg InsertOrderConsiderationParams) error
	InsertOrderOffer(ctx context.Context, arg InsertOrderOfferParams) error
	UpdateOrderIsCancelled(ctx context.Context, arg UpdateOrderIsCancelledParams) error
	UpdateOrderIsValidated(ctx context.Context, arg UpdateOrderIsValidatedParams) error
}

var _ Querier = (*Queries)(nil)
