// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresql

import (
	"context"
	"encoding/json"
)

type Querier interface {
	DestroyOrders(ctx context.Context, arg DestroyOrdersParams) error
	GetJsonOrder(ctx context.Context, orderHash string) (json.RawMessage, error)
	GetOrder(ctx context.Context, orderHash string) (GetOrderRow, error)
	GetOrderConsideration(ctx context.Context, orderHash string) ([]GetOrderConsiderationRow, error)
	GetOrderHashByItemConsideration(ctx context.Context, arg GetOrderHashByItemConsiderationParams) ([]string, error)
	GetOrderHashByItemOffer(ctx context.Context, arg GetOrderHashByItemOfferParams) ([]string, error)
	GetOrderOffer(ctx context.Context, orderHash string) ([]GetOrderOfferRow, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	InsertOrderConsideration(ctx context.Context, arg InsertOrderConsiderationParams) error
	InsertOrderOffer(ctx context.Context, arg InsertOrderOfferParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
