// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: collection.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/tabbed/pqtype"
)

const getCollection = `-- name: GetCollection :many
SELECT token, owner, co.name, ca.name as category, description, metadata, created_at
FROM collections co
         JOIN categories ca on co.category = ca.id
WHERE (token ILIKE $1 or $1 IS NULL)
  AND (owner ILIKE $2 or $2 IS NULL)
  AND (co.name ILIKE $3 or $3 IS NULL)
  AND (ca.name ILIKE $4 or $4 IS NULL)
OFFSET $5
LIMIT $6
`

type GetCollectionParams struct {
	Token    sql.NullString
	Owner    sql.NullString
	Name     sql.NullString
	Category sql.NullString
	Offset   int32
	Limit    int32
}

type GetCollectionRow struct {
	Token       string
	Owner       string
	Name        string
	Category    string
	Description string
	Metadata    pqtype.NullRawMessage
	CreatedAt   sql.NullTime
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) ([]GetCollectionRow, error) {
	rows, err := q.db.QueryContext(ctx, getCollection,
		arg.Token,
		arg.Owner,
		arg.Name,
		arg.Category,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCollectionRow{}
	for rows.Next() {
		var i GetCollectionRow
		if err := rows.Scan(
			&i.Token,
			&i.Owner,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionWithCategory = `-- name: GetCollectionWithCategory :many
SELECT token, owner, co.name, ca.name as category, description, metadata, created_at
FROM collections co
         JOIN categories ca on co.category = ca.id
WHERE ca.name ILIKE $1
OFFSET $2
LIMIT $3
`

type GetCollectionWithCategoryParams struct {
	Category sql.NullString
	Offset   int32
	Limit    int32
}

type GetCollectionWithCategoryRow struct {
	Token       string
	Owner       string
	Name        string
	Category    string
	Description string
	Metadata    pqtype.NullRawMessage
	CreatedAt   sql.NullTime
}

func (q *Queries) GetCollectionWithCategory(ctx context.Context, arg GetCollectionWithCategoryParams) ([]GetCollectionWithCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionWithCategory, arg.Category, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCollectionWithCategoryRow{}
	for rows.Next() {
		var i GetCollectionWithCategoryRow
		if err := rows.Scan(
			&i.Token,
			&i.Owner,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCollection = `-- name: InsertCollection :one
INSERT INTO "collections" ("token", "owner", "name", "description","category", "metadata")
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING token, owner, name, description, metadata, category, created_at
`

type InsertCollectionParams struct {
	Token       string
	Owner       string
	Name        string
	Description string
	Category    int32
	Metadata    pqtype.NullRawMessage
}

func (q *Queries) InsertCollection(ctx context.Context, arg InsertCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, insertCollection,
		arg.Token,
		arg.Owner,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Metadata,
	)
	var i Collection
	err := row.Scan(
		&i.Token,
		&i.Owner,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}
