// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: collection.sql

package postgresql

import (
	"context"

	"github.com/tabbed/pqtype"
)

const insertCollection = `-- name: InsertCollection :one
INSERT INTO "collections" ("token", "owner", "name", "description","category", "metadata")
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING token, owner, name, description, metadata, category, created_at
`

type InsertCollectionParams struct {
	Token       string
	Owner       string
	Name        string
	Description string
	Category    int32
	Metadata    pqtype.NullRawMessage
}

func (q *Queries) InsertCollection(ctx context.Context, arg InsertCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, insertCollection,
		arg.Token,
		arg.Owner,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Metadata,
	)
	var i Collection
	err := row.Scan(
		&i.Token,
		&i.Owner,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}
