// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: marketplace.sql

package postgresql

import (
	"context"
)

const getMarketplaceLastSyncBlock = `-- name: GetMarketplaceLastSyncBlock :one
SELECT "last_sync_block"
FROM "marketplace"
LIMIT 1
`

func (q *Queries) GetMarketplaceLastSyncBlock(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMarketplaceLastSyncBlock)
	var last_sync_block int64
	err := row.Scan(&last_sync_block)
	return last_sync_block, err
}

const updateMarketplaceLastSyncBlock = `-- name: UpdateMarketplaceLastSyncBlock :exec
UPDATE "marketplace"
SET "last_sync_block" = $1
WHERE true
`

func (q *Queries) UpdateMarketplaceLastSyncBlock(ctx context.Context, lastSyncBlock int64) error {
	_, err := q.db.ExecContext(ctx, updateMarketplaceLastSyncBlock, lastSyncBlock)
	return err
}
