// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package postgresql

import ()

type Listing struct {
	ListingID   string `json:"listing_id"`
	Collection  string `json:"collection"`
	TokenID     string `json:"token_id"`
	Seller      string `json:"seller"`
	Price       string `json:"price"`
	Status      string `json:"status"`
	BlockNumber string `json:"block_number"`
	TxIndex     int64  `json:"tx_index"`
}

type Nft struct {
	TokenID      string `json:"token_id"`
	ContractAddr string `json:"contract_addr"`
	Owner        string `json:"owner"`
	IsBurned     bool   `json:"is_burned"`
	BlockNumber  string `json:"block_number"`
	TxIndex      int64  `json:"tx_index"`
}
