// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresql

import (
	"github.com/tabbed/pqtype"
)

type Listing struct {
	ListingID    string
	ContractAddr string
	TokenID      string
	Seller       string
	Price        string
	Status       string
	BlockNumber  string
	TxIndex      int64
}

type Nft struct {
	TokenID      string
	ContractAddr string
	Owner        string
	IsBurned     bool
	Metadata     pqtype.NullRawMessage
	BlockNumber  string
	TxIndex      int64
}
