// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: nft.sql

package postgresql

import (
	"context"
	"database/sql"
)

const getNft = `-- name: GetNft :many
SELECT n.token_id, n.contract_addr, n.owner, n.is_burned, l.listing_id, l.seller, l.price
FROM "nfts" n
LEFT JOIN "listings" l ON n.token_id = l.token_id AND n.contract_addr = l.contract_addr
WHERE (l.status = 'Open' OR l.listing_id IS NULL)
AND (n.contract_addr ILIKE $1 OR $1 IS NULL)
AND (n.owner ILIKE $2 OR l.seller ILIKE $2 OR $2 IS NULL)
OFFSET $3
LIMIT $4
`

type GetNftParams struct {
	ContractAddr sql.NullString `json:"contract_addr"`
	Owner        sql.NullString `json:"owner"`
	Offset       int32          `json:"offset"`
	Limit        int32          `json:"limit"`
}

type GetNftRow struct {
	TokenID      string         `json:"token_id"`
	ContractAddr string         `json:"contract_addr"`
	Owner        string         `json:"owner"`
	IsBurned     bool           `json:"is_burned"`
	ListingID    sql.NullString `json:"listing_id"`
	Seller       sql.NullString `json:"seller"`
	Price        sql.NullString `json:"price"`
}

func (q *Queries) GetNft(ctx context.Context, arg GetNftParams) ([]GetNftRow, error) {
	rows, err := q.db.QueryContext(ctx, getNft,
		arg.ContractAddr,
		arg.Owner,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNftRow{}
	for rows.Next() {
		var i GetNftRow
		if err := rows.Scan(
			&i.TokenID,
			&i.ContractAddr,
			&i.Owner,
			&i.IsBurned,
			&i.ListingID,
			&i.Seller,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNft = `-- name: UpsertNft :exec
INSERT INTO "nfts" (token_id, contract_addr, owner, is_burned, block_number, tx_index)
VALUES ($1,$2,$3,$4, $5, $6)
ON CONFLICT (token_id, contract_addr) DO UPDATE
SET owner=$3,is_burned=$4,block_number=$5, tx_index=$6
WHERE $5 > nfts.block_number OR ($5 = nfts.block_number AND $6 > nfts.tx_index)
`

type UpsertNftParams struct {
	TokenID      string `json:"token_id"`
	ContractAddr string `json:"contract_addr"`
	Owner        string `json:"owner"`
	IsBurned     bool   `json:"is_burned"`
	BlockNumber  string `json:"block_number"`
	TxIndex      int64  `json:"tx_index"`
}

func (q *Queries) UpsertNft(ctx context.Context, arg UpsertNftParams) error {
	_, err := q.db.ExecContext(ctx, upsertNft,
		arg.TokenID,
		arg.ContractAddr,
		arg.Owner,
		arg.IsBurned,
		arg.BlockNumber,
		arg.TxIndex,
	)
	return err
}
