// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresql

import (
	"context"
)

type Querier interface {
	GetNft(ctx context.Context, arg GetNftParams) (GetNftRow, error)
	SearchValidListingNft(ctx context.Context, arg SearchValidListingNftParams) ([]SearchValidListingNftRow, error)
	UpsertListing(ctx context.Context, arg UpsertListingParams) error
	UpsertNft(ctx context.Context, arg UpsertNftParams) error
}

var _ Querier = (*Queries)(nil)
